#!/bin/bash
if [ ! -f "/etc/uuid" ]; then
  /usr/bin/uuidgen > /etc/uuid
fi

UUID=`cat /etc/uuid`
CARD=`aplay -l | grep BossDAC`
DIGI=`echo $CARD | grep -i digi`
CARD="BossDAC"

DRIVER=`aplay -l | grep "pcm512x-hifi-0" | awk -F\[ '{print $2}' | awk -F\] '{print $1}'`
VERSION=`cat /etc/hifiberry.version`

DIGIFIXED=0
DIGIDOP=0
LINEARVOLUME=0

echo Configuring RAAT server for UUID $UUID on $CARD \($DRIVER\)

# Generate correct mixer controls:
VOLCTL='"volume": { "type": "software" }'
MAXFS=384000
DSD=""
SIGNALTYPE="digital"

PLAYBACKDEVICE="default"

cat <<END >/etc/hifiberry_raat.conf
{
    "vendor":      "HiFiBerry",
    "model":       "$CARD",
    "unique_id":   "$UUID",
    "output":      { "type": "alsa", 
                     "device": "$PLAYBACKDEVICE",
                     "max_pcm_rate": $MAXFS,
                     $DSD
                     "signal_path": [ { "quality": "lossless", "type": "output", "method": "$SIGNALTYPE" } ],
		     "supported_formats": [ 
                         {"sample_type": "pcm", "sample_rate": 44100, "bits_per_sample": 16, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 44100, "bits_per_sample": 24, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 44100, "bits_per_sample": 32, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 88200, "bits_per_sample": 16, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 88200, "bits_per_sample": 24, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 88200, "bits_per_sample": 32, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 176400, "bits_per_sample": 16, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 176400, "bits_per_sample": 24, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 176400, "bits_per_sample": 32, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 48000, "bits_per_sample": 16, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 48000, "bits_per_sample": 24, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 48000, "bits_per_sample": 32, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 96000, "bits_per_sample": 16, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 96000, "bits_per_sample": 24, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 96000, "bits_per_sample": 32, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 192000, "bits_per_sample": 16, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 192000, "bits_per_sample": 24, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 192000, "bits_per_sample": 32, "channels": 2}
                         {"sample_type": "pcm", "sample_rate": 384000, "bits_per_sample": 16, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 384000, "bits_per_sample": 24, "channels": 2},
                         {"sample_type": "pcm", "sample_rate": 384000, "bits_per_sample": 32, "channels": 2}
                     ]
                   },
$VOLCTL
    "version":     "$VERSION",
    "transport":   { "type": "alloboss" }
}
END

